# Generated by Django 3.2.10 on 2021-12-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which ticket types are displayed (0, 1, 2, ...).', verbose_name='display order'),
        ),
    ]
