# Generated by Django 3.2.9 on 2021-12-20 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='event',
            field=models.ForeignKey(blank=True, help_text='If not set, will be shown for all events.', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='event'),
        ),
        migrations.AddConstraint(
            model_name='eventpage',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='event_pages_with_unique_slugs'),
        ),
    ]
