# Generated by Django 3.2.10 on 2022-01-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_tickettype_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notice',
            field=models.TextField(blank=True, help_text='Notice to be shown on top of each page, if set.', verbose_name='notice'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable ', verbose_name='payment enabled'),
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
