# Generated by Django 3.2.12 on 2022-02-19 22:07

from django.db import migrations, models
import django.utils.timezone


def ticket_set_paid(apps, schema_editor):
    for row in apps.get_model('events', 'Ticket').objects.all():
        if row.status in ('OKPD', 'USED'):
            row.paid = True
            row.save(update_fields=['paid'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_tickettype_can_pay_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('admin', 'Administrative'), ('online', 'Online'), ('onsite', 'On-site')], default='admin', max_length=16, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(ticket_set_paid, reverse_code=migrations.RunPython.noop)
    ]
