# Generated by Django 3.2.10 on 2021-12-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_org_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='age_gate',
            field=models.BooleanField(default=True, help_text='Is the attendee of age?', verbose_name='age gate'),
            preserve_default=False,
        ),
    ]
