# Generated by Django 3.2.12 on 2022-02-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220219_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='org_email',
            field=models.EmailField(blank=True, help_text='If set, mails for these applications will be sent to the provided address, not the global event address.', max_length=254, verbose_name='org email'),
        ),
    ]
