# Generated by Django 3.2.10 on 2021-12-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_ticket_age_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtype',
            name='template',
            field=models.TextField(help_text='Template for dynamic application form fields. Docs: https://github.com/DragoonAethis/Coriolis/wiki/Dynamic-Application-Forms', verbose_name='template'),
        ),
    ]
