# Generated by Django 3.2.12 on 2022-02-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_notificationchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('CNCL', 'Cancelled'), ('WAIT', 'Waiting for Organizers'), ('WPAY', 'Waiting for online payment'), ('OKNP', 'Ready (payment on site)'), ('OKPD', 'Ready (paid)'), ('USED', 'Used')], default='WAIT', max_length=4, verbose_name='status'),
        ),
    ]
