# Generated by Django 3.2.10 on 2021-12-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_applicationtype_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='city',
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='template',
            field=models.TextField(help_text='Szablon dla dynamicznych pól formularzy w zgłoszeniach. Dokumentacja: https://github.com/DragoonAethis/Coriolis/wiki/Dynamic-Application-Forms', verbose_name='template'),
        ),
    ]
