# Generated by Django 3.2.12 on 2022-02-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='vaccination_proof',
            field=models.CharField(choices=[('none', 'None'), ('weak', 'Weak'), ('strong', 'Strong')], default='none', help_text='How sure are we that a given attendee is vaccinated?', max_length=16, verbose_name='vaccination proof'),
        ),
    ]
