# Generated by Django 3.2.10 on 2021-12-31 16:48

from django.db import migrations, models
import events.utils


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20211230_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='preview_box_coords',
            field=models.CharField(blank=True, help_text='Box coords for the ticket preview generator. Docs: https://github.com/DragoonAethis/Coriolis/wiki/Ticket-Preview-Generator', max_length=32, verbose_name='preview box coords'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Used for generating ticket previews.', upload_to=events.utils.get_ticket_preview_path, verbose_name='preview image'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, help_text='Printed on the customized ticket.', upload_to='', verbose_name='image'),
        ),
    ]
