# Generated by Django 3.2.12 on 2022-02-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_ticket_vaccination_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='on_site_registration',
            field=models.BooleanField(default=True, help_text='Determines if the ticket can be purchased on-site.', verbose_name='on-site registration'),
        ),
    ]
