# Generated by Django 3.2.10 on 2021-12-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20211231_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='preview',
            field=models.ImageField(blank=True, help_text='Automatically generated preview image.', upload_to='', verbose_name='preview'),
        ),
    ]
