# Generated by Django 3.2.12 on 2022-02-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_tickettype_on_site_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='configuration',
            field=models.JSONField(help_text='Channel target configuration, in JSON. See docs: https://github.com/DragoonAethis/Coriolis/wiki/Notification-Channels', verbose_name='configuration'),
        ),
    ]
