# Generated by Django 3.2.12 on 2022-02-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_notificationchannel_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='emails_enabled',
            field=models.BooleanField(default=True, help_text='Toggles emails for some status changes on this event.', verbose_name='emails enabled'),
        ),
    ]
