# Generated by Django 3.2.12 on 2022-02-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_emails_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prometheus_key',
            field=models.CharField(blank=True, help_text='Key used as the password for the Prometheus metrics URL', max_length=256, verbose_name='prometheus key'),
        ),
    ]
