# Generated by Django 3.2.13 on 2022-04-14 15:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_prometheus_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
