# Generated by Django 4.1.3 on 2022-11-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_alter_tickettype_special_payment_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="applications_require_registration",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, users must register for the event before sending applications.",
                verbose_name="applications require registration",
            ),
        ),
    ]
