# Generated by Django 4.1.3 on 2022-11-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_event_applications_require_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="answers",
            field=models.JSONField(default={}, verbose_name="answers"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="notes",
            field=models.TextField(default="", verbose_name="notes"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="application",
            field=models.TextField(
                help_text="Legacy application answers field.",
                verbose_name="application",
            ),
        ),
    ]
