# Generated by Django 4.1.4 on 2022-12-09 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_alter_application_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketRenderer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                (
                    "config",
                    models.JSONField(
                        help_text="Coriolis configuration for this renderer. See wiki/docs for more info on this."
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_renderer_help_text",
            field=models.TextField(
                blank=True,
                help_text="Text to be shown under the custom image upload field (image dimensions, notices).",
                verbose_name="ticket renderer help text",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_renderer_variants",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of ticket variants to render. The first one will be shown to users.",
                max_length=256,
                verbose_name="ticket renderer variants",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_renderer",
            field=models.ForeignKey(
                help_text="System used to render the ticket images.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.ticketrenderer",
                verbose_name="ticket renderer",
            ),
        ),
    ]
