# Generated by Django 4.1.5 on 2023-01-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_remove_tickettype_preview_box_coords_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettype",
            name="purchase_rate_limit_secs",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Determines if users have to wait between purchases of this ticket type. Useful for sale fairness of high-demand tickets. Set to 0 to disable this feature, or the number of seconds to make users wait after purchasing.",
                verbose_name="purchase rate limit seconds",
            ),
        ),
    ]
