# Generated by Django 4.1.6 on 2023-02-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_ticket_shirt_size_tickettype_can_specify_shirt_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventpage",
            options={
                "verbose_name": "event page",
                "verbose_name_plural": "event pages",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketrenderer",
            options={
                "verbose_name": "ticket renderer",
                "verbose_name_plural": "ticket renderers",
            },
        ),
        migrations.AlterField(
            model_name="application",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="application",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
    ]
