# Generated by Django 4.1.6 on 2023-02-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0027_alter_eventpage_options_alter_ticketrenderer_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="exempt_from_2fa",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, this user does not have to enable 2FA even if the usual security policies would enforce it.",
                verbose_name="exempt from 2FA",
            ),
        ),
    ]
