# Generated by Django 4.1.6 on 2023-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0030_ticket_override_price_ticket_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="sale_closed_notice",
            field=models.TextField(
                blank=True,
                help_text="Notice to be shown instead of the default one when the ticket sales are closed.",
                verbose_name="sale closed notice",
            ),
        ),
    ]
