# Generated by Django 4.1.7 on 2023-02-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0031_event_sale_closed_notice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="sale_closed_notice",
            field=models.TextField(
                blank=True,
                help_text="Notice to be shown instead of the default one when the ticket sales are closed. May contain HTML.",
                verbose_name="sale closed notice",
            ),
        ),
        migrations.AlterField(
            model_name="notificationchannel",
            name="target",
            field=models.CharField(
                choices=[
                    ("discord-webhook", "Discord Webhook"),
                    ("telegram-message", "Telegram Message"),
                ],
                help_text="Where to send events from this channel?",
                max_length=16,
                verbose_name="target",
            ),
        ),
    ]
