# Generated by Django 4.2.5 on 2023-10-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0035_unify_ticket_ready_status_20231002_0129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("CNCL", "Cancelled"),
                    ("WAIT", "Waiting for Organizers"),
                    ("WPAY", "Waiting for online payment"),
                    ("OKNP", "Ready"),
                    ("USED", "Used"),
                ],
                default="WAIT",
                max_length=4,
                verbose_name="status",
            ),
        ),
    ]
