# Generated by Django 4.2.5 on 2023-10-02 04:44

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0040_remove_tickettype_can_pay_online_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="contributed_value",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="PLN",
                help_text="Collected ticket value to count in the exported metrics.",
                max_digits=10,
                verbose_name="contributed value",
            ),
        ),
    ]
