# Generated by Django 4.2.5 on 2023-10-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0041_alter_ticket_contributed_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="private_notes",
            field=models.TextField(
                blank=True, help_text="Private org notes, visible only in the admin panel", verbose_name="private notes"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="private_notes",
            field=models.TextField(
                blank=True, help_text="Private org notes, visible only in the admin panel", verbose_name="private notes"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="notes",
            field=models.TextField(blank=True, help_text="User notes, visible to users/orgs", verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_notes",
            field=models.TextField(blank=True, help_text="Org notes, visible to users/orgs", verbose_name="org notes"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="notes",
            field=models.TextField(blank=True, help_text="Public notes, visible to users/orgs", verbose_name="notes"),
        ),
    ]
