# Generated by Django 4.2.5 on 2023-10-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0042_application_private_notes_ticket_private_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="status_deadline",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Date/time until which the current status is valid. The system will automatically update the ticket after this date as needed.",
                null=True,
                verbose_name="status deadline",
            ),
        ),
        migrations.AddField(
            model_name="tickettype",
            name="online_payment_window",
            field=models.PositiveIntegerField(
                default=0,
                help_text="If online payment is required, how many minutes should we wait for a valid payment? A ticket is cancelled automatically when time's up. Setting this to zero disables automatic cancellation.",
                verbose_name="online payment window",
            ),
        ),
    ]
