# Generated by Django 4.2.6 on 2023-10-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0044_remove_event_applications_require_registration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtype",
            name="submission_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Message to be displayed after successfully submitting a form. If empty, a default 'orgs will be in touch soon' message is shown.",
                verbose_name="submission message",
            ),
        ),
        migrations.AlterField(
            model_name="applicationtype",
            name="template",
            field=models.TextField(
                help_text="Template for dynamic application form fields. Docs: https://github.com/DragoonAethis/Coriolis/wiki/Dynamic-Application-Forms",
                verbose_name="template",
            ),
        ),
    ]
