# Generated by Django 4.2.6 on 2023-10-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0045_applicationtype_submission_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="application",
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["slug"], name="events_even_slug_30eb0f_idx"),
        ),
    ]
