# Generated by Django 4.2.7 on 2023-11-10 21:19

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def update_personalization_dates(apps, schema_editor):
    model = apps.get_model("events", "TicketType")
    model.objects.all().update(personalization_to=F("registration_to"))


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0047_alter_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettype",
            name="personalization_to",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                help_text="Until when the ticket can be personalized?",
                verbose_name="personalization to",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="payment_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable or disable online payments on this event.",
                verbose_name="payment enabled",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="ticket_renderer",
            field=models.ForeignKey(
                help_text="System used to render the personalized ticket images.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.ticketrenderer",
                verbose_name="ticket renderer",
            ),
        ),
        migrations.RunPython(update_personalization_dates),
    ]
