# Generated by Django 4.2.7 on 2023-11-10 23:34

from django.db import migrations, models

import events.utils


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0048_tickettype_personalization_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationtype",
            name="org_email",
            field=models.CharField(
                blank=True,
                db_column="org_email",
                help_text="If set, mails for these applications will be sent to the provided addresses, not the global event address. This can be a comma-separated list of emails.",
                validators=[events.utils.validate_multiple_emails],
                verbose_name="org emails",
            ),
        ),
        migrations.RenameField(
            model_name="applicationtype",
            old_name="org_email",
            new_name="org_emails",
        ),
    ]
