# Generated by Django 4.2.7 on 2023-12-01 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0049_alter_applicationtype_org_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="customization_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The person who approved customizations on a ticket.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_customized_ticket_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="personalization approved by",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="customization_approved_on",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Date/time on which the ticket customizations were approved.",
                null=True,
                verbose_name="personalization approved on",
            ),
        ),
    ]
