# Generated by Django 4.2.9 on 2024-01-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0051_tickettype_upgrade_priority_ticketflag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="flags",
            field=models.ManyToManyField(
                help_text="Flags specific to this ticket added on top of the type flags.",
                to="events.ticketflag",
                verbose_name="flags",
            ),
        ),
    ]
