# Generated by Django 4.2.9 on 2024-01-25 20:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0053_alter_ticket_flags_alter_tickettype_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventOrg",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                (
                    "target_ticket_count",
                    models.PositiveSmallIntegerField(verbose_name="target ticket count"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="event",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "source_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.application",
                        verbose_name="source application",
                    ),
                ),
                (
                    "target_ticket_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.tickettype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="original_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The original ticket type, as it was set while joining the organization.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="events.tickettype",
                verbose_name="original type",
            ),
        ),
        migrations.CreateModel(
            name="EventOrgBillingDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                (
                    "tax_id",
                    models.CharField(max_length=32, verbose_name="tax identifier"),
                ),
                ("address", models.CharField(max_length=256, verbose_name="address")),
                ("postcode", models.CharField(max_length=256, verbose_name="postcode")),
                ("city", models.CharField(max_length=256, verbose_name="city")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="event",
                    ),
                ),
                (
                    "event_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventorg",
                        verbose_name="event org",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="org",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The organization this ticket belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.eventorg",
                verbose_name="org",
            ),
        ),
    ]
