# Generated by Django 4.2.9 on 2024-01-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0056_alter_eventorgbillingdetails_event_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventorgbillingdetails",
            name="representative",
            field=models.CharField(
                default="", max_length=256, verbose_name="representative"
            ),
            preserve_default=False,
        ),
    ]
