# Generated by Django 4.2.10 on 2024-02-07 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0057_eventorgbillingdetails_representative"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventorg",
            options={"verbose_name": "event org", "verbose_name_plural": "event orgs"},
        ),
        migrations.AlterModelOptions(
            name="eventorgbillingdetails",
            options={
                "verbose_name": "event org billing details",
                "verbose_name_plural": "event org billing details",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketflag",
            options={
                "verbose_name": "ticket flag",
                "verbose_name_plural": "ticket flags",
            },
        ),
    ]
