# Generated by Django 4.2.10 on 2024-02-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0058_alter_eventorg_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="accreditation_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes shown during accreditation.",
                verbose_name="accreditation notes",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="issued_identifier",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="issued identifier"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="stop_on_accreditation",
            field=models.BooleanField(
                default=False,
                help_text="Prevent the accreditation from letting this ticket through. Accreditation coordinator must manually handle the ticket.",
                verbose_name="stop on accreditation",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Public notes, visible to users/orgs, but not to accreditation.",
                verbose_name="notes",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="private_notes",
            field=models.TextField(
                blank=True,
                help_text="Private org notes, visible only in the admin panel.",
                verbose_name="private notes",
            ),
        ),
    ]
