# Generated by Django 4.2.10 on 2024-02-17 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0059_ticket_accreditation_notes_ticket_issued_identifier_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "permissions": [
                    ("crew_accreditation", "Can access the crew accreditation panel."),
                    ("crew_mod_queue", "Can access the crew mod queue."),
                    ("crew_orgs", "Can access the crew organization lists."),
                    (
                        "crew_orgs_view_billing_details",
                        "Can access the org billing details from the crew panel.",
                    ),
                ],
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
    ]
