# Generated by Django 4.2.16 on 2024-10-13 23:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0062_alter_application_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgePublicKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly public key name to be used as its unique identifier.",
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="The name may contain ASCII letters, numbers, underscores and dashes only.",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("age-x25519", "Age-native X25519 Public Key (age1...)"),
                            ("ssh-ed25519", "SSH Ed25519 Public Key (ssh-ed25519 ...)"),
                        ],
                        verbose_name="kind",
                    ),
                ),
                (
                    "pubkey",
                    models.CharField(
                        help_text="The public key to use for cryptographic operations.",
                        max_length=2048,
                        verbose_name="pubkey",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Age public key",
                "verbose_name_plural": "Age public keys",
            },
        ),
        migrations.AddConstraint(
            model_name="agepublickey",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="pubkey_names_unique_in_event"
            ),
        ),
    ]
