# Generated by Django 4.2.16 on 2024-11-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0063_agepublickey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtype",
            name="display_deadline",
            field=models.BooleanField(
                default=False,
                help_text="Publicly display the application form closure date.",
                verbose_name="display deadline",
            ),
        ),
    ]
