# Generated by Django 4.2.16 on 2024-12-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0064_applicationtype_display_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="force_display_ticket_details_in_crew_panel",
            field=models.BooleanField(
                default=False,
                help_text="Force display all data for tickets, even if they cannot be acted upon. Useful for quick data lookups before the event.",
                verbose_name="force display ticket details in crew panel",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="If disabled, hides this event from the front page picker.",
                verbose_name="event active",
            ),
        ),
    ]
