# Generated by Django 4.2.17 on 2025-01-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0065_event_force_display_ticket_details_in_crew_panel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="banner",
            field=models.TextField(
                blank=True,
                help_text="Banner/MOTD (uses Markdown), visible to users on the front page and in the application details",
                verbose_name="banner",
            ),
        ),
    ]
