# Generated by Django 4.2.17 on 2025-01-06 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0066_application_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="events.ticket",
                verbose_name="ticket",
            ),
        ),
        migrations.AddField(
            model_name="applicationtype",
            name="label_selector",
            field=models.CharField(
                blank=True,
                help_text="Selects the answer field from the application template to display as a Label in the Application admin.",
                max_length=128,
                verbose_name="label selector",
            ),
        ),
    ]
