# Generated by Django 4.2.18 on 2025-02-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0067_application_ticket_applicationtype_label_selector"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtype",
            name="secret_keys",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Secret keys that can be used to submit an application after the deadline or without the required ticket. Append '?key=...' to the application URL to use them. Single key per line, lines starting with '#' are comments.",
                verbose_name="secret keys",
            ),
        ),
    ]
