# Generated by Django 4.2.19 on 2025-02-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0069_alter_ticket_contributed_value_currency_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "permissions": [
                    ("crew_accreditation", "Can access the crew accreditation panel."),
                    ("crew_mod_queue", "Can access the crew mod queue."),
                    ("crew_orgs", "Can access the crew organization lists."),
                    (
                        "crew_orgs_view_invoices",
                        "Can access the org invoices from the crew panel.",
                    ),
                    (
                        "crew_orgs_view_billing_details",
                        "Can access the org billing details from the crew panel.",
                    ),
                ],
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
    ]
