# Generated by Django 4.2.19 on 2025-02-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0070_alter_event_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventorg",
            name="location_tag",
            field=models.CharField(
                blank=True,
                help_text="Map location or another identifier that makes it easier to locate this org in on-site operations.",
                max_length=256,
                verbose_name="location tag",
            ),
        ),
    ]
