# Generated by Django 4.2.19 on 2025-02-14 18:12

import django.core.files.storage
from django.db import migrations, models
import events.models.orgs
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0072_alter_event_options_eventorgtask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventorginvoice",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Downloadable file with the invoice contents.",
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/home/dragoon/Code/Coriolis/private"
                    )
                ),
                upload_to=events.models.orgs.get_invoice_upload_dir,
                verbose_name="file",
            ),
        ),
    ]
