# Generated by Django 4.2.19 on 2025-02-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0073_alter_eventorginvoice_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("online", "Online"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=16,
                verbose_name="payment method",
            ),
        ),
    ]
