# Generated by Django 4.2.21 on 2025-07-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0075_event_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Event cover image to be displayed on the event front page.",
                upload_to="",
                verbose_name="cover image",
            ),
        ),
    ]
