# Generated by Django 4.2.21 on 2025-07-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0076_event_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Event cover image to be displayed on the event front page.",
                upload_to="backgrounds",
                verbose_name="cover image",
            ),
        ),
    ]
