# Generated by Django 4.2.21 on 2025-07-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0077_alter_event_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Optional city name for statistical purposes.",
                max_length=256,
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Event cover image to be displayed on the event front page. Aim for 512px width and ~256px height.",
                upload_to="backgrounds",
                verbose_name="cover image",
            ),
        ),
    ]
