# Generated by Django 4.2.25 on 2025-12-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0078_ticket_city_alter_event_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtype",
            name="self_service_waiting_for_applicant",
            field=models.BooleanField(
                default=False,
                help_text="When an application has the 'Waiting for Applicant' status, enabling this adds Approve/Reject buttons for the user to switch the status to Approved/Rejected on their own.",
                verbose_name="self-service waiting for applicant",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("CNCL", "Cancelled"),
                    ("WAIT", "Waiting for Organizers"),
                    ("WAPL", "Waiting for Applicant"),
                    ("RSVE", "On Reserve List"),
                    ("APRV", "Accepted"),
                    ("REJD", "Rejected"),
                ],
                default="WAIT",
                max_length=4,
                verbose_name="status",
            ),
        ),
    ]
