# Generated by Django 5.2.11 on 2026-02-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0001_squashed_0079_applicationtype_self_service_waiting_for_applicant_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refund_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="refund data"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_title",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="refund title"
            ),
        ),
    ]
