# Generated by Django 5.2.11 on 2026-02-27 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0080_payment_refund_data_payment_refund_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="approved"),
                ),
                (
                    "scheduled",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="scheduled"
                    ),
                ),
                (
                    "executed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="executed"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default="0.00", max_digits=9),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="refund title"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.payment",
                        verbose_name="payment",
                    ),
                ),
            ],
        ),
    ]
